name: Remote SSH 
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Serve
    runs-on: ubuntu-latest
    steps:
      - name: Execute ssh commands on host
        uses: actions/checkout@v2
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          script: |
            cd OC-Bot
            npm run update
